module.exports = {
  someSidebar: {
    'Глава 1': [
      'chapter-1/alfabe',
      'chapter-1/pronouns',
      {
        Глаголы: [
          'chapter-1/verbs-roots',
          'chapter-1/verbs-present',
          'chapter-1/verbs-future',
          'chapter-1/verbs-transitive-intransitive',
          'chapter-1/verbs-past',
          'chapter-1/sentence-structure',
          'chapter-1/questioning-sentence',
          {
            Примеры: [
              'chapter-1/examples/verbs-to-be',
              'chapter-1/examples/verbs-to-do',
              'chapter-1/examples/verbs-to-say',
              'chapter-1/examples/verbs-to-see',
              'chapter-1/examples/verbs-to-go',
              'chapter-1/examples/verbs-to-bring',
              'chapter-1/examples/verbs-to-come',
              'chapter-1/examples/verbs-to-walk',
              'chapter-1/examples/verbs-to-can',
              'chapter-1/examples/verbs-to-know',
            ],
          },

          // "chapter-1/question-words",
        ],
      },
    ],
    'Глава 2': [
      'chapter-2/demonstrative-pronouns',
      'chapter-2/verb-exists',
      'chapter-2/question-words',
      'chapter-2/subjunctive-mood',
      'chapter-2/verb-have-exists',
      'chapter-2/verbs-with-prefixes',
      'chapter-2/imperative-mood',
      'chapter-2/helper-verb',
      'chapter-2/numbers',
      {
        Примеры: [
          'chapter-2/examples/rakirin',
          'chapter-2/examples/rabun',
          'chapter-2/examples/nivisin',
          'chapter-2/examples/xwendin',
          'chapter-2/examples/xwarin',
          'chapter-2/examples/xwestin',
          'chapter-2/examples/pirsin',
          'chapter-2/examples/hez-kirin',
          'chapter-2/examples/jiyan',
          'chapter-2/examples/mirin',
          'chapter-2/examples/nerin',
        ],
      },
    ],
    'Глава 3': [
      'chapter-3/indirect-case',
      'chapter-3/noun-pairs',
      'chapter-3/word-formation',
      'chapter-3/nouns-plural-and-singular',
      'chapter-3/sentence-structure-2',
      {
        Примеры: [
          'chapter-3/examples/soz-dayin',
          'chapter-3/examples/qerar-dayin',
          'chapter-3/examples/guh-dayin',
          'chapter-3/examples/birin',
        ],
      },
    ],
    'Глава 4': [
      'chapter-4/izafet',
      'chapter-4/adjectives',
      'chapter-4/vocabulary',
      'chapter-4/personality-traits-vocabulary',
      'chapter-4/xwe',
      {
        Примеры: [
          'chapter-4/examples/azad-kirin',
          'chapter-4/examples/mezin-buyin',
          'chapter-4/examples/xwes-hatin',
          'chapter-4/examples/zelal-kirin',
        ],
      },
    ],
    'Глава 5': [
      'chapter-5/prepositions',
      'chapter-5/preposition-and-move',
      'chapter-5/preposition-in-place',
      'chapter-5/preposition-ji',
      'chapter-5/preposition-bi',
      'chapter-5/preposition-about-for-because',
      'chapter-5/preposition-shorthands',
      {
        Примеры: [
          'chapter-5/examples/bawer-kirin',
          'chapter-5/examples/bawer-anin',
          'chapter-5/examples/bawer-buyin',
        ],
      },
    ],
    'Глава 6': [
      'chapter-6/numerics',
      'chapter-6/word-creation',
      'chapter-6/all-nobody',
      'chapter-6/how-often',
    ],
    'Глава 7': [
      'chapter-7/verbs-past-continuous-multiple',
      'chapter-7/verbs-perfect',
      'chapter-7/verbs-past-perfect',
      'chapter-7/verbs-with-prefixes',
    ],
    'Глава 8': [
      'chapter-8/types-of-action',
      'chapter-8/transition-of-a-verb-into-states-into-action–verbs-and-vice-versa',
      'chapter-8/passive',
    ],
    'Глава 9': ['chapter-9/verbs-conditional-form', 'chapter-9/causative'],
  },
};
